### ISSUE TITLE
Python interface to thunder-streaming

### ISSUE THREAD

**Issue by andrewosh** [freeman-lab/thunder-streaming#5]
In order to prevent too much context-switching among experimenters currently used to the Thunder/IPython combo, we should create a Python client for Thunder-Streaming that: 

a) Lets experimenters specify a set of analyses to run, and where the results of those analyses should be sent (Lightning, print, disk, etc.) 
b) Potentially displays output from Thunder-Streaming in an easy-to-read way (interfaces well with IPython for direct embedding of a Lightning dashboard, perhaps) 

The current proposal is to use YAML as a configuration file format, referencing precompiled analyses by their (fully-qualified?) class names. Something like this: 

```
analysis: 
    name: org.project.thunder.streaming.clustering.KMeans
    output: 
        type: lightning
        host: http://1.2.3.4
        port: 5454
analysis: 
    name: org.project.thunder.streaming.analyses.SimpleStats
    output: 
        type: disk
        path: /path/to/results/
```
